# taken from -- https://github.com/plausible/hosting/blob/master/docker-compose.yml
version: "3.3"

services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./services/plausible/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PLAUSIBLE_POSTGRES_PASSWORD}
    labels:
      - "traefik.enable=false"

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./services/plausible/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./services/plausible/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    labels:
      - "traefik.enable=false"

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    # ports:
    #   - 8000:8000
    env_file:
      - ./services/plausible/conf.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plausible.rule=Host(`plausible.${DOMAIN_NAME}`)"
      - "traefik.http.routers.plausible.entryPoints=http"
      - "traefik.http.routers.plausible.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.plausible_tls.rule=Host(`plausible.${DOMAIN_NAME}`)"
      - "traefik.http.routers.plausible_tls.entryPoints=https"
      - "traefik.http.routers.plausible_tls.tls.certresolver=mydnschallenge"
      - "traefik.http.services.plausible.loadbalancer.server.port=8000"

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
